server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false&serverTimezone=UTC
    username: root
    password: 13801874064guoyu
    driver-class-name: com.mysql.cj.jdbc.Driver
#      discovery:
#        cluster-name: SH # 配置集群名称，也就是机房位置，例如：HZ杭州,SH上海
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka/  # eureka本身也是一个服务，所以会将自己注册上去


