server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false&serverTimezone=UTC
    username: root
    password: 13801874064guoyu
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: order-service # order服务的服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos注册中心地址
      discovery:
        # cluster-name: HZ # nacos集群名称
        namespace: public # nacos命名空间
        ephemeral: false # 设置为非临时实例
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
user-service: # 给某个微服务配置负载均衡规则，这里是user-service服务
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡策略
ribbon:
  eager-load:
    enabled: true # 启动时就去加载所有服务，提高响应速度
    clients: user-service # 指定饥饿加载的服务名称
